// <auto-generated />
using EFCoreDB.DataStorage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCoreDB.DataStorage.Migrations
{
    [DbContext(typeof(EFCoreDBDataContext))]
    partial class EFCoreDBDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMAddressCC", b =>
                {
                    b.Property<int>("FDMAddressCCPrimaryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FDMBloggerCCForeignKey")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FDMAddressCCPrimaryKey");

                    b.HasIndex("FDMBloggerCCForeignKey")
                        .IsUnique();

                    b.ToTable("FDMAddressCC");
                });

            modelBuilder.Entity("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMBlogCC", b =>
                {
                    b.Property<int>("FDMBlogCCPrimaryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FDMProcessCCForeignKey")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FDMBlogCCPrimaryKey");

                    b.HasIndex("FDMProcessCCForeignKey")
                        .IsUnique();

                    b.ToTable("FDMBlogCC");
                });

            modelBuilder.Entity("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMBloggerCC", b =>
                {
                    b.Property<int>("FDMBloggerCCPrimaryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FDMBlogCCForeignKey")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FDMBloggerCCPrimaryKey");

                    b.HasIndex("FDMBlogCCForeignKey")
                        .IsUnique();

                    b.ToTable("FDMBloggerCC");
                });

            modelBuilder.Entity("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMGroupCC", b =>
                {
                    b.Property<int>("FDMGroupCCPrimaryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FDMProcessCCForeignKey")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FDMGroupCCPrimaryKey");

                    b.HasIndex("FDMProcessCCForeignKey");

                    b.ToTable("FDMGroupCC");
                });

            modelBuilder.Entity("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMPointCC", b =>
                {
                    b.Property<int>("FDMPointCCPrimaryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FDMGroupCCForeignKey")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FDMPointCCPrimaryKey");

                    b.HasIndex("FDMGroupCCForeignKey");

                    b.ToTable("FDMPointCC");
                });

            modelBuilder.Entity("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMPostCC", b =>
                {
                    b.Property<int>("FDMPostCCPrimaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FDMBlogCCForeignKey")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FDMPostCCPrimaryId");

                    b.HasIndex("FDMBlogCCForeignKey");

                    b.ToTable("FDMPostCC");
                });

            modelBuilder.Entity("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMProcessCC", b =>
                {
                    b.Property<int>("FDMProcessCCPrimaryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FDMProcessCCPrimaryKey");

                    b.ToTable("FDMProcessCC");
                });

            modelBuilder.Entity("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMTagCC", b =>
                {
                    b.Property<int>("FDMTagCCPrimaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FDMTagCCPrimaryId");

                    b.ToTable("FDMTagCC");
                });

            modelBuilder.Entity("FDMPostCCFDMTagCC", b =>
                {
                    b.Property<int>("PostListFDMPostCCPrimaryId")
                        .HasColumnType("int");

                    b.Property<int>("TagListFDMTagCCPrimaryId")
                        .HasColumnType("int");

                    b.HasKey("PostListFDMPostCCPrimaryId", "TagListFDMTagCCPrimaryId");

                    b.HasIndex("TagListFDMTagCCPrimaryId");

                    b.ToTable("PostTags");
                });

            modelBuilder.Entity("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMAddressCC", b =>
                {
                    b.HasOne("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMBloggerCC", "FDMBloggerCC")
                        .WithOne("FDMAddressCC")
                        .HasForeignKey("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMAddressCC", "FDMBloggerCCForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FDMBloggerCC");
                });

            modelBuilder.Entity("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMBlogCC", b =>
                {
                    b.HasOne("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMProcessCC", "FDMProcessCC")
                        .WithOne("FDMBlogCC")
                        .HasForeignKey("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMBlogCC", "FDMProcessCCForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FDMProcessCC");
                });

            modelBuilder.Entity("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMBloggerCC", b =>
                {
                    b.HasOne("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMBlogCC", "FDMBlogCC")
                        .WithOne("FDMBloggerCC")
                        .HasForeignKey("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMBloggerCC", "FDMBlogCCForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FDMBlogCC");
                });

            modelBuilder.Entity("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMGroupCC", b =>
                {
                    b.HasOne("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMProcessCC", "FDMProcessCC")
                        .WithMany("GroupList")
                        .HasForeignKey("FDMProcessCCForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FDMProcessCC");
                });

            modelBuilder.Entity("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMPointCC", b =>
                {
                    b.HasOne("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMGroupCC", "FDMGroupCC")
                        .WithMany("PointList")
                        .HasForeignKey("FDMGroupCCForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FDMGroupCC");
                });

            modelBuilder.Entity("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMPostCC", b =>
                {
                    b.HasOne("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMBlogCC", "FDMBlogCC")
                        .WithMany("PostList")
                        .HasForeignKey("FDMBlogCCForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FDMBlogCC");
                });

            modelBuilder.Entity("FDMPostCCFDMTagCC", b =>
                {
                    b.HasOne("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMPostCC", null)
                        .WithMany()
                        .HasForeignKey("PostListFDMPostCCPrimaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMTagCC", null)
                        .WithMany()
                        .HasForeignKey("TagListFDMTagCCPrimaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMBlogCC", b =>
                {
                    b.Navigation("FDMBloggerCC");

                    b.Navigation("PostList");
                });

            modelBuilder.Entity("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMBloggerCC", b =>
                {
                    b.Navigation("FDMAddressCC");
                });

            modelBuilder.Entity("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMGroupCC", b =>
                {
                    b.Navigation("PointList");
                });

            modelBuilder.Entity("EFCoreDB.Models.ConventionalConfiguration.FullyDefinedModels.FDMProcessCC", b =>
                {
                    b.Navigation("FDMBlogCC");

                    b.Navigation("GroupList");
                });
#pragma warning restore 612, 618
        }
    }
}
